# Generated by Django 4.2.7 on 2023-12-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
