# Generated by Django 4.2.7 on 2023-12-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='business',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='business_listings.business'),
        ),
    ]
