# Generated by Django 5.0 on 2023-12-19 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0006_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='business_listings.business'),
        ),
    ]
