# Generated by Django 5.0 on 2023-12-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_listings', '0008_alter_reviewrating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business',
        ),
    ]
